version: '3.9'

networks:
  mynetwork:
    driver: bridge

services:
  redis1:
    image: bitnami/redis:latest
    container_name: redis1
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data-1:/bitnami/redis/data
    networks:
      - mynetwork

  redis2:
    image: bitnami/redis:latest
    container_name: redis2
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data-2:/bitnami/redis/data
    networks:
      - mynetwork

  redis3:
    image: bitnami/redis:latest
    container_name: redis3
    ports:
      - "6381:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data-3:/bitnami/redis/data
    networks:
      - mynetwork
      
  redis4:
    image: bitnami/redis:latest
    container_name: redis4
    ports:
      - "6382:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data-4:/bitnami/redis/data
    networks:
      - mynetwork
  #  
  #redis5:
  #  image: bitnami/redis:latest
  #  container_name: redis5
  #  ports:
  #    - "6383:6379"
  #  environment:
  #    - ALLOW_EMPTY_PASSWORD=yes
  #  volumes:
  #    - redis-data-5:/bitnami/redis/data
  #  networks:
  #    - mynetwork
  #  
  #redis6:
  #  image: bitnami/redis:latest
  #  container_name: redis6
  #  ports:
  #    - "6384:6379"
  #  environment:
  #    - ALLOW_EMPTY_PASSWORD=yes
  #  volumes:
  #    - redis-data-6:/bitnami/redis/data
  #  networks:
  #    - mynetwork
  #  
  #redis7:
  #  image: bitnami/redis:latest
  #  container_name: redis7
  #  ports:
  #    - "6385:6379"
  #  environment:
  #    - ALLOW_EMPTY_PASSWORD=yes
  #  volumes:
  #    - redis-data-7:/bitnami/redis/data
  #  networks:
  #    - mynetwork
  #  
  #redis8:
  #  image: bitnami/redis:latest
  #  container_name: redis8
  #  ports:
  #    - "6386:6379"
  #  environment:
  #    - ALLOW_EMPTY_PASSWORD=yes
  #  volumes:
  #    - redis-data-8:/bitnami/redis/data
  #  networks:
  #    - mynetwork

  redis-init:
    image: bitnami/redis:latest
    container_name: redis-init
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      #- redis5
      #- redis6
      #- redis7
      #- redis8
    volumes:
      - ./init-redis.sh:/usr/local/bin/init-redis.sh
    entrypoint: ["/usr/local/bin/init-redis.sh"]
    networks:
      - mynetwork

  dns-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dns-api
    ports:
      - "5000:5000"
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      #- redis5
      #- redis6
      #- redis7
      #- redis8
    networks:
      - mynetwork
    volumes:
      - ./data:/app/data

  grpc-dns-server:
    build:
      context: ./grpc-server
      dockerfile: Dockerfile
    container_name: grpc-dns-server
    ports:
      - "50051:50051"
    depends_on:
      - dns-api
    networks:
      - mynetwork

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540" 
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      #- redis5
      #- redis6
      #- redis7
      #- redis8
    networks:
      - mynetwork
    volumes:
      - redis-insight-data:/db

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:
  redis-data-4:
  #redis-data-5:
  #redis-data-6:
  #redis-data-7:
  #redis-data-8:
  redis-insight-data:
